name: Terraform_apply_pipeline
run-name: terraform_provision
on: [workflow_dispatch]
jobs:
  terraform_apply:
    runs-on: self-hosted
    steps:
      - name: using DevSecOps Repo
        uses: actions/checkout@v4
        with:
          repository: manojpadigineti-cloud/DevSecOps
        env:
          vault_token: ${{ secrets.VAULT_TOKEN }}
      - run: |
          cd /actions-runner/_work/github_actions_pipelines/github_actions_pipelines/terraform/AWS/roboshop_project/roboshop_instances/dev/ ; terraform init -backend-config=backends.tfvars
          terraform apply -var-file=dev.tfvars -var "vault_token=$vault_token" -auto-approve