name: Terraform_apply_pipeline
run-name: terraform_provision
on: [workflow_dispatch]
jobs:
  terraform_apply:
    runs-on: self-hosted
    steps:
      - name: Checkout DevSecOps Repo
        uses: actions/checkout@v4
        with:
          repository: manojpadigineti-cloud/DevSecOps
      - name: Terraform Init & Apply
        run: |
          cd /actions-runner/_work/github_actions_pipelines/github_actions_pipelines/terraform/AWS/roboshop_project/roboshop_instances
          git pull
          terraform init -backend-config=dev/backends.tfvars
          terraform apply -var-file=dev/dev.tfvars -var vault_token="$VAULT_TOKEN" -auto-approve
        env:
          VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}
